###对张量(tensor)的基本运用：

In [26]:
import torch
from math import * 

### 1. 创建一个5行3列的随机张量X

In [10]:
X = torch.rand(5, 3)
print(X)

tensor([[0.9424, 0.8813, 0.8589],
        [0.3661, 0.7537, 0.3092],
        [0.1006, 0.4463, 0.4801],
        [0.1152, 0.7584, 0.3923],
        [0.6182, 0.8093, 0.0336]])


### 2. 用pytorch内置函数检测X的shape，dtype，device

In [11]:
print(X.shape)
print(X.dtype)
print(X.device)

torch.Size([5, 3])
torch.float32
cpu


### 3. 直接创建一个[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]的张量Y

In [12]:
Y = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(Y)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])


### 4. 用任意方法将Y的维度转变为5行3列

In [17]:
Y = Y.T
print(Y)

tensor([[ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14],
        [ 5, 10, 15]])


### 5. 实现X和Y的加减乘除，同时了解abs()，sqrt()，neg()，mean()的作用

In [30]:
print("X+Y")
print(X+Y)

print("X-Y")
print(X-Y)

print("X*Y")
print(X*Y)

print("X/Y")
print(X/Y)



X+Y
tensor([[ 1.9424,  6.8813, 11.8589],
        [ 2.3661,  7.7537, 12.3092],
        [ 3.1006,  8.4463, 13.4801],
        [ 4.1152,  9.7584, 14.3923],
        [ 5.6182, 10.8093, 15.0336]])
X-Y
tensor([[ -0.0576,  -5.1187, -10.1411],
        [ -1.6339,  -6.2463, -11.6908],
        [ -2.8994,  -7.5537, -12.5199],
        [ -3.8848,  -8.2416, -13.6077],
        [ -4.3818,  -9.1907, -14.9664]])
X*Y
tensor([[0.9424, 5.2876, 9.4478],
        [0.7323, 5.2756, 3.7104],
        [0.3019, 3.5708, 6.2413],
        [0.4608, 6.8252, 5.4917],
        [3.0912, 8.0933, 0.5036]])
X/Y
tensor([[0.9424, 0.1469, 0.0781],
        [0.1831, 0.1077, 0.0258],
        [0.0335, 0.0558, 0.0369],
        [0.0288, 0.0843, 0.0280],
        [0.1236, 0.0809, 0.0022]])


In [33]:
print("abs(X-Y)")
print(abs(X-Y))

print("sqrt(X)")
print(torch.sqrt(X))

print("torch.neg(X)")#取反
print(torch.neg(X))

print("torch.mean(X)")
print(torch.mean(X))

abs(X-Y)
tensor([[ 0.0576,  5.1187, 10.1411],
        [ 1.6339,  6.2463, 11.6908],
        [ 2.8994,  7.5537, 12.5199],
        [ 3.8848,  8.2416, 13.6077],
        [ 4.3818,  9.1907, 14.9664]])
sqrt(X)
tensor([[0.9708, 0.9388, 0.9268],
        [0.6051, 0.8681, 0.5561],
        [0.3172, 0.6681, 0.6929],
        [0.3394, 0.8708, 0.6263],
        [0.7863, 0.8996, 0.1832]])
torch.neg(X)
tensor([[-0.9424, -0.8813, -0.8589],
        [-0.3661, -0.7537, -0.3092],
        [-0.1006, -0.4463, -0.4801],
        [-0.1152, -0.7584, -0.3923],
        [-0.6182, -0.8093, -0.0336]])
torch.mean(X)
tensor(0.5244)


### 6. *了解内置函数max()，argmax()，sum()，同时知道其内参dim的作用

In [40]:
print(X)
print("torch.max(X)")
print(torch.max(X))

print("torch.argmax(X)")
print(torch.argmax(X))#最大值索引

print("torch.sum(X)")
print(torch.sum(X))

tensor([[0.9424, 0.8813, 0.8589],
        [0.3661, 0.7537, 0.3092],
        [0.1006, 0.4463, 0.4801],
        [0.1152, 0.7584, 0.3923],
        [0.6182, 0.8093, 0.0336]])
torch.max(X)
tensor(0.9424)
torch.argmax(X)
tensor(0)
torch.sum(X)
tensor(7.8657)


In [39]:
print("dim = 0")
print(torch.argmax(X,dim = 0))#每列最大值索引

print("dim = 1")
print(torch.argmax(X,dim = 1))#每行最大值索引

dim = 0
tensor([0, 0, 0])
dim = 1
tensor([0, 1, 2, 1, 1])


### 7. 将张量X转为Numpy格式，再将其转回来。

In [44]:
X_n = X.numpy()
print(X_n)
print(type(X_n))

X_n_p = torch.from_numpy(X_n)
print(X_n_p)
print(type(X_n_p))

[[0.9424377  0.88127494 0.85889125]
 [0.366143   0.7536526  0.30920273]
 [0.10063541 0.44634563 0.48010284]
 [0.1152029  0.7583604  0.39226633]
 [0.6182359  0.8093324  0.03357303]]
<class 'numpy.ndarray'>
tensor([[0.9424, 0.8813, 0.8589],
        [0.3661, 0.7537, 0.3092],
        [0.1006, 0.4463, 0.4801],
        [0.1152, 0.7584, 0.3923],
        [0.6182, 0.8093, 0.0336]])
<class 'torch.Tensor'>


###  8. 将张量X放到cuda上。

In [50]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

X.to(device)



tensor([[0.9424, 0.8813, 0.8589],
        [0.3661, 0.7537, 0.3092],
        [0.1006, 0.4463, 0.4801],
        [0.1152, 0.7584, 0.3923],
        [0.6182, 0.8093, 0.0336]], device='cuda:0')

###  9. *学会张量的拼接，解压，压缩，广播，以及Numpy的transpose函数

#### 拼接:
两个矩阵有一个维度相等时，将 Tensor 拼接，  
dim = 0 拼接行  
dim = 1 拼接列

In [63]:
print(X.shape)
print(Y.shape)

X_Y=torch.cat((X,Y),0)
print(X_Y)
print(X_Y.shape)

Y_X=torch.cat((X,Y),1)
print(Y_X)
print(Y_X.shape)

torch.Size([5, 3])
torch.Size([5, 3])
tensor([[ 0.9424,  0.8813,  0.8589],
        [ 0.3661,  0.7537,  0.3092],
        [ 0.1006,  0.4463,  0.4801],
        [ 0.1152,  0.7584,  0.3923],
        [ 0.6182,  0.8093,  0.0336],
        [ 1.0000,  6.0000, 11.0000],
        [ 2.0000,  7.0000, 12.0000],
        [ 3.0000,  8.0000, 13.0000],
        [ 4.0000,  9.0000, 14.0000],
        [ 5.0000, 10.0000, 15.0000]])
torch.Size([10, 3])
tensor([[ 0.9424,  0.8813,  0.8589,  1.0000,  6.0000, 11.0000],
        [ 0.3661,  0.7537,  0.3092,  2.0000,  7.0000, 12.0000],
        [ 0.1006,  0.4463,  0.4801,  3.0000,  8.0000, 13.0000],
        [ 0.1152,  0.7584,  0.3923,  4.0000,  9.0000, 14.0000],
        [ 0.6182,  0.8093,  0.0336,  5.0000, 10.0000, 15.0000]])
torch.Size([5, 6])


#### 广播:  
对两个形状不同的 Tensor 运算时，复制元素使这两个 Tensor 形状相同,再运算。  
每个维度的大小要么相等，要么其中一个为 1

In [66]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([1, 2])
tensor([1, 2, 3])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0