## 对张量(tensor)的基本运用：

In [2]:
import torch
from math import * 
import numpy as np

### 1. 创建一个5行3列的随机张量X

In [3]:
X = torch.rand(5, 3)
print(X)

tensor([[0.9886, 0.3915, 0.8914],
        [0.3526, 0.4581, 0.7538],
        [0.5626, 0.4342, 0.0579],
        [0.9975, 0.7517, 0.6457],
        [0.1060, 0.3721, 0.4581]])


### 2. 用pytorch内置函数检测X的shape，dtype，device

In [4]:
print(X.shape)
print(X.dtype)
print(X.device)

torch.Size([5, 3])
torch.float32
cpu


### 3. 直接创建一个[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]的张量Y

In [4]:
Y = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(Y)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])


### 4. 用任意方法将Y的维度转变为5行3列

In [5]:
Y = Y.T
print(Y)

tensor([[ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14],
        [ 5, 10, 15]])


### 5. 实现X和Y的加减乘除，同时了解abs()，sqrt()，neg()，mean()的作用

In [6]:
print("X+Y")
print(X+Y)

print("X-Y")
print(X-Y)

print("X*Y")
print(X*Y)

print("X/Y")
print(X/Y)



X+Y
tensor([[ 1.0335,  6.0669, 11.3923],
        [ 2.9544,  7.3519, 12.8369],
        [ 3.2137,  8.7159, 13.9203],
        [ 4.6374,  9.9826, 14.6312],
        [ 5.9654, 10.4838, 15.0634]])
X-Y
tensor([[ -0.9665,  -5.9331, -10.6077],
        [ -1.0456,  -6.6481, -11.1631],
        [ -2.7863,  -7.2841, -12.0797],
        [ -3.3626,  -8.0174, -13.3688],
        [ -4.0346,  -9.5162, -14.9366]])
X*Y
tensor([[ 0.0335,  0.4015,  4.3148],
        [ 1.9088,  2.4630, 10.0432],
        [ 0.6411,  5.7272, 11.9643],
        [ 2.5498,  8.8431,  8.8372],
        [ 4.8272,  4.8376,  0.9511]])
X/Y
tensor([[0.0335, 0.0112, 0.0357],
        [0.4772, 0.0503, 0.0697],
        [0.0712, 0.0895, 0.0708],
        [0.1594, 0.1092, 0.0451],
        [0.1931, 0.0484, 0.0042]])


In [7]:
print("abs(X-Y)")
print(abs(X-Y))

print("sqrt(X)")
print(torch.sqrt(X))

print("torch.neg(X)")# 取反
print(torch.neg(X))

print("torch.mean(X)")
print(torch.mean(X))

abs(X-Y)
tensor([[ 0.9665,  5.9331, 10.6077],
        [ 1.0456,  6.6481, 11.1631],
        [ 2.7863,  7.2841, 12.0797],
        [ 3.3626,  8.0174, 13.3688],
        [ 4.0346,  9.5162, 14.9366]])
sqrt(X)
tensor([[0.1829, 0.2587, 0.6263],
        [0.9769, 0.5932, 0.9148],
        [0.4623, 0.8461, 0.9593],
        [0.7984, 0.9912, 0.7945],
        [0.9826, 0.6955, 0.2518]])
torch.neg(X)
tensor([[-0.0335, -0.0669, -0.3923],
        [-0.9544, -0.3519, -0.8369],
        [-0.2137, -0.7159, -0.9203],
        [-0.6374, -0.9826, -0.6312],
        [-0.9654, -0.4838, -0.0634]])
torch.mean(X)
tensor(0.5500)


### 6. *了解内置函数max()，argmax()，sum()，同时知道其内参dim的作用

In [8]:
print(X)
print("torch.max(X)")
print(torch.max(X))

print("torch.argmax(X)")
print(torch.argmax(X))# 最大值索引

print("torch.sum(X)")
print(torch.sum(X))

tensor([[0.0335, 0.0669, 0.3923],
        [0.9544, 0.3519, 0.8369],
        [0.2137, 0.7159, 0.9203],
        [0.6374, 0.9826, 0.6312],
        [0.9654, 0.4838, 0.0634]])
torch.max(X)
tensor(0.9826)
torch.argmax(X)
tensor(10)
torch.sum(X)
tensor(8.2496)


In [9]:
print("dim = 0")
print(torch.argmax(X,dim = 0))# 每列最大值索引

print("dim = 1")
print(torch.argmax(X,dim = 1))# 每行最大值索引

dim = 0
tensor([4, 3, 2])
dim = 1
tensor([2, 0, 2, 1, 0])


### 7. 将张量X转为Numpy格式，再将其转回来。

In [10]:
X_n = X.numpy()
print(X_n)
print(type(X_n))

X_n_p = torch.from_numpy(X_n)
print(X_n_p)
print(type(X_n_p))

[[0.03347009 0.06691724 0.39225447]
 [0.95441085 0.35186088 0.83693016]
 [0.21371311 0.71590036 0.92032945]
 [0.6374431  0.98256755 0.6312259 ]
 [0.9654492  0.48376137 0.06340355]]
<class 'numpy.ndarray'>
tensor([[0.0335, 0.0669, 0.3923],
        [0.9544, 0.3519, 0.8369],
        [0.2137, 0.7159, 0.9203],
        [0.6374, 0.9826, 0.6312],
        [0.9654, 0.4838, 0.0634]])
<class 'torch.Tensor'>


###  8. 将张量X放到cuda上。

In [11]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

X.to(device)



tensor([[0.0335, 0.0669, 0.3923],
        [0.9544, 0.3519, 0.8369],
        [0.2137, 0.7159, 0.9203],
        [0.6374, 0.9826, 0.6312],
        [0.9654, 0.4838, 0.0634]], device='cuda:0')

###  9. *学会张量的拼接，解压，压缩，广播，以及Numpy的transpose函数

#### 拼接:
两个矩阵有一个维度相等时，将 Tensor 拼接，  
dim = 0 拼接行  
dim = 1 拼接列

In [12]:
print(X.shape)
print(Y.shape)

X_Y=torch.cat((X,Y),0)
print(X_Y)
print(X_Y.shape)

Y_X=torch.cat((X,Y),1)
print(Y_X)
print(Y_X.shape)

torch.Size([5, 3])
torch.Size([5, 3])
tensor([[ 0.0335,  0.0669,  0.3923],
        [ 0.9544,  0.3519,  0.8369],
        [ 0.2137,  0.7159,  0.9203],
        [ 0.6374,  0.9826,  0.6312],
        [ 0.9654,  0.4838,  0.0634],
        [ 1.0000,  6.0000, 11.0000],
        [ 2.0000,  7.0000, 12.0000],
        [ 3.0000,  8.0000, 13.0000],
        [ 4.0000,  9.0000, 14.0000],
        [ 5.0000, 10.0000, 15.0000]])
torch.Size([10, 3])
tensor([[ 0.0335,  0.0669,  0.3923,  1.0000,  6.0000, 11.0000],
        [ 0.9544,  0.3519,  0.8369,  2.0000,  7.0000, 12.0000],
        [ 0.2137,  0.7159,  0.9203,  3.0000,  8.0000, 13.0000],
        [ 0.6374,  0.9826,  0.6312,  4.0000,  9.0000, 14.0000],
        [ 0.9654,  0.4838,  0.0634,  5.0000, 10.0000, 15.0000]])
torch.Size([5, 6])


#### 压缩：
将输入 Tensor 中的一维数据删除（降维打击！）。
当给定dim时，只在给定维度上操作。

In [13]:
m = torch.zeros(2,1,2,1,2)
print(m.size())
m_s = torch.squeeze(m)
print(m_s.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])


#### 解压：
扩展维度，对输入的位置插入一个维度

In [14]:
print(m_s.size())
m_s_us = torch.unsqueeze(m_s, 0)
print(m_s_us.size())

torch.Size([2, 2, 2])
torch.Size([1, 2, 2, 2])


#### 广播:  
对两个形状不同的 Tensor 运算时，复制元素使这两个 Tensor 形状相同,再运算。 

如果两个张量维度不同(维数不同)，扩展维度小的，使其与另一个张量相同。
如果两个张量某个维度不同（在同一维度上大小不同），但其中一个张量的一个维度大小为 1，在这个维度扩展，使其与另一个张量相同。

In [15]:
a = torch.tensor([[1]])
b = torch.tensor([[1],[2],[3]])
c = torch.tensor([[1,2],[3,4],[5,6]])
print(a)
print(b)
print(c)
print(a + b)# 情况1
print(b + c)# 情况2

tensor([[1]])
tensor([[1],
        [2],
        [3]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[2],
        [3],
        [4]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])


#### Numpy的transpose函数  
转置二维数组

In [16]:
print(c.numpy())
print(c.numpy().transpose())

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
