## 对张量(tensor)的基本运用：

In [1]:
import torch
import math
import numpy as np

### 1. 创建一个5行3列的随机张量X

In [2]:
X = torch.rand(5, 3)
print(X)

tensor([[0.8727, 0.7831, 0.6232],
        [0.6307, 0.4965, 0.1589],
        [0.2637, 0.6801, 0.3841],
        [0.9899, 0.0247, 0.9769],
        [0.7091, 0.5102, 0.5920]])


### 2. 用pytorch内置函数检测X的shape，dtype，device

In [3]:
print(X.shape)
print(X.dtype)
print(X.device)

torch.Size([5, 3])
torch.float32
cpu


### 3. 直接创建一个[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]的张量Y

In [4]:
Y = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(Y)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])


### 4. 用任意方法将Y的维度转变为5行3列

In [5]:
Y = Y.T
print(Y)

tensor([[ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14],
        [ 5, 10, 15]])


### 5. 实现X和Y的加减乘除，同时了解abs()，sqrt()，neg()，mean()的作用

In [6]:
print("X+Y")
print(X+Y)

print("X-Y")
print(X-Y)

print("X*Y")
print(X*Y)

print("X/Y")
print(X/Y)



X+Y
tensor([[ 1.8727,  6.7831, 11.6232],
        [ 2.6307,  7.4965, 12.1589],
        [ 3.2637,  8.6801, 13.3841],
        [ 4.9899,  9.0247, 14.9769],
        [ 5.7091, 10.5102, 15.5920]])
X-Y
tensor([[ -0.1273,  -5.2169, -10.3768],
        [ -1.3693,  -6.5035, -11.8411],
        [ -2.7363,  -7.3199, -12.6159],
        [ -3.0101,  -8.9753, -13.0231],
        [ -4.2909,  -9.4898, -14.4080]])
X*Y
tensor([[ 0.8727,  4.6983,  6.8550],
        [ 1.2614,  3.4755,  1.9063],
        [ 0.7911,  5.4408,  4.9929],
        [ 3.9595,  0.2227, 13.6761],
        [ 3.5454,  5.1017,  8.8800]])
X/Y
tensor([[0.8727, 0.1305, 0.0567],
        [0.3154, 0.0709, 0.0132],
        [0.0879, 0.0850, 0.0295],
        [0.2475, 0.0027, 0.0698],
        [0.1418, 0.0510, 0.0395]])


In [7]:
print("math.abs(X-Y)")
print(abs(X-Y))

print("math.sqrt(X)")
print(torch.sqrt(X))

print("torch.neg(X)")# 取反
print(torch.neg(X))

print("torch.mean(X)")
print(torch.mean(X))

math.abs(X-Y)
tensor([[ 0.1273,  5.2169, 10.3768],
        [ 1.3693,  6.5035, 11.8411],
        [ 2.7363,  7.3199, 12.6159],
        [ 3.0101,  8.9753, 13.0231],
        [ 4.2909,  9.4898, 14.4080]])
math.sqrt(X)
tensor([[0.9342, 0.8849, 0.7894],
        [0.7942, 0.7046, 0.3986],
        [0.5135, 0.8247, 0.6197],
        [0.9949, 0.1573, 0.9884],
        [0.8421, 0.7143, 0.7694]])
torch.neg(X)
tensor([[-0.8727, -0.7831, -0.6232],
        [-0.6307, -0.4965, -0.1589],
        [-0.2637, -0.6801, -0.3841],
        [-0.9899, -0.0247, -0.9769],
        [-0.7091, -0.5102, -0.5920]])
torch.mean(X)
tensor(0.5797)


### 6. *了解内置函数max()，argmax()，sum()，同时知道其内参dim的作用

In [8]:
print(X)
print("torch.max(X)")
print(torch.max(X))

print("torch.argmax(X)")
print(torch.argmax(X))# 最大值索引

print("torch.sum(X)")
print(torch.sum(X))

tensor([[0.8727, 0.7831, 0.6232],
        [0.6307, 0.4965, 0.1589],
        [0.2637, 0.6801, 0.3841],
        [0.9899, 0.0247, 0.9769],
        [0.7091, 0.5102, 0.5920]])
torch.max(X)
tensor(0.9899)
torch.argmax(X)
tensor(9)
torch.sum(X)
tensor(8.6956)


In [9]:
print("dim = 0")
print(torch.argmax(X,dim = 0))# 每列最大值索引

print("dim = 1")
print(torch.argmax(X,dim = 1))# 每行最大值索引

dim = 0
tensor([3, 0, 3])
dim = 1
tensor([0, 0, 1, 0, 0])


### 7. 将张量X转为Numpy格式，再将其转回来。

In [10]:
X_n = X.numpy()
print(X_n)
print(type(X_n))

X_n_p = torch.from_numpy(X_n)
print(X_n_p)
print(type(X_n_p))

[[0.8726941  0.78305244 0.6231803 ]
 [0.6307074  0.496507   0.1588561 ]
 [0.26369596 0.6800956  0.384071  ]
 [0.98987097 0.02474755 0.9768649 ]
 [0.70908177 0.5101712  0.59200114]]
<class 'numpy.ndarray'>
tensor([[0.8727, 0.7831, 0.6232],
        [0.6307, 0.4965, 0.1589],
        [0.2637, 0.6801, 0.3841],
        [0.9899, 0.0247, 0.9769],
        [0.7091, 0.5102, 0.5920]])
<class 'torch.Tensor'>


###  8. 将张量X放到cuda上。

In [11]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

X.to(device)



tensor([[0.8727, 0.7831, 0.6232],
        [0.6307, 0.4965, 0.1589],
        [0.2637, 0.6801, 0.3841],
        [0.9899, 0.0247, 0.9769],
        [0.7091, 0.5102, 0.5920]], device='cuda:0')

###  9. *学会张量的拼接，解压，压缩，广播，以及Numpy的transpose函数

#### 拼接:
两个矩阵有一个维度相等时，将 Tensor 拼接，  
dim = 0 拼接行  
dim = 1 拼接列

In [12]:
print(X.shape)
print(Y.shape)

X_Y=torch.cat((X,Y),0)
print(X_Y)
print(X_Y.shape)

Y_X=torch.cat((X,Y),1)
print(Y_X)
print(Y_X.shape)

torch.Size([5, 3])
torch.Size([5, 3])
tensor([[ 0.8727,  0.7831,  0.6232],
        [ 0.6307,  0.4965,  0.1589],
        [ 0.2637,  0.6801,  0.3841],
        [ 0.9899,  0.0247,  0.9769],
        [ 0.7091,  0.5102,  0.5920],
        [ 1.0000,  6.0000, 11.0000],
        [ 2.0000,  7.0000, 12.0000],
        [ 3.0000,  8.0000, 13.0000],
        [ 4.0000,  9.0000, 14.0000],
        [ 5.0000, 10.0000, 15.0000]])
torch.Size([10, 3])
tensor([[ 0.8727,  0.7831,  0.6232,  1.0000,  6.0000, 11.0000],
        [ 0.6307,  0.4965,  0.1589,  2.0000,  7.0000, 12.0000],
        [ 0.2637,  0.6801,  0.3841,  3.0000,  8.0000, 13.0000],
        [ 0.9899,  0.0247,  0.9769,  4.0000,  9.0000, 14.0000],
        [ 0.7091,  0.5102,  0.5920,  5.0000, 10.0000, 15.0000]])
torch.Size([5, 6])


#### 压缩：
将输入 Tensor 中的一维数据删除（降维打击！）。
当给定dim时，只在给定维度上操作。

In [13]:
m = torch.zeros(2,1,2,1,2)
print(m.size())
m_s = torch.squeeze(m)
print(m_s.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])


#### 解压：
扩展维度，对输入的位置插入一个维度

In [14]:
print(m_s.size())
m_s_us = torch.unsqueeze(m_s, 0)
print(m_s_us.size())

torch.Size([2, 2, 2])
torch.Size([1, 2, 2, 2])


#### 广播:  
对两个形状不同的 Tensor 运算时，复制元素使这两个 Tensor 形状相同,再运算。 

如果两个张量维度不同(维数不同)，扩展维度小的，使其与另一个张量相同。
如果两个张量某个维度不同（在同一维度上大小不同），但其中一个张量的一个维度大小为 1，在这个维度扩展，使其与另一个张量相同。

In [15]:
a = torch.tensor([[1]])
b = torch.tensor([[1],[2],[3]])
c = torch.tensor([[1,2],[3,4],[5,6]])
print(a)
print(b)
print(c)
print(a + b)# 情况1
print(b + c)# 情况2

tensor([[1]])
tensor([[1],
        [2],
        [3]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[2],
        [3],
        [4]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])


#### Numpy的transpose函数  
转置二维数组

In [16]:
print(c.numpy())
print(c.numpy().transpose())

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
